#!/bin/bash

set -euo pipefail

:usage() {
    sed -r 's/^([ ]{4}|\t)//g' <<USAGE
    pdns records add

    Usage:
        pdns records add -n <name> -t <type> -c <content> -d <domain_id> [-r]
        pdns records add -h

    Options:
        -n <name>      Specify record name.
        -t <type>      Specify record type (example: CNAME).
        -c <content>   Specify record content (address).
        -d <domain_id> Specify record domain id.
        -r             Dry run.
        -h             Show this screen.
USAGE
}

:main() {
    local content=""
    local name=""
    local type=""
    local domain_id=""

    local dryrun=false

    while getopts ":c:n:t:d:r" key; do
        case "$key" in
            c)
                content="$OPTARG"
                ;;

            n)
                name="$OPTARG"
                ;;

            t)
                type="$OPTARG"
                ;;

            d)
                domain_id="$OPTARG"
                ;;

            r)
                dryrun=true
                ;;

            h)
                :usage
                exit 0
                ;;
        esac
    done
    local OPTIND # reset options

    (
        :source_config
        true $user $host $password $name
    )

    if [ ! "$content" ] \
    || [ ! "$name" ] \
    || [ ! "$type" ] \
    || [ ! "$domain_id" ];
    then
        :usage
        exit 1
    fi
    local query="INSERT INTO records SET"
    query="$query name = '$name'"
    query="$query, content = '$content'"
    query="$query, type = '$type'"
    query="$query, domain_id = $domain_id"


    if $dryrun; then
        :log "$query"
        :log "dry run mode, exiting"
        exit 0
    else
        :execute "$query"
    fi
}
:execute() {
    local query="$1"

    (
        :source_config
        mysql -h"$host" -u"$user" -p"$password" "$name" -vv <<< "$query"
    )
}

:main "$@"
