#!/bin/bash

:usage() {
    sed -r 's/^([ ]{4}|\t)//g' <<USAGE
    pdns records - working with pdns records

    Usage:
        pdns records <command> [command-options]

    Commands:
        list     List pdns records using specified filter.
        add      Add pdns records with specified values.
        remove   Remove specified records.
USAGE
}

:main() {
    local _lib=$(dirname "$(readlink -f "$0")")

    if [ $# -eq 0 ]; then
        :usage
        exit 0
    fi

    if _command=$(:command_exists "$1"); then
        shift
        "$_command" "$@"
        exit $?
    fi

    echo "unknown command" >&2
    exit 1
}

:command_exists() {
    local command_name="$1"
    if [ -f "$_lib/pdns-records-$command_name" ]; then
        echo "$_lib/pdns-records-$command_name"
        return 0
    else
        return 1
    fi
}

:main "$@"
